#!/usr/bin/env bash
# install-system.sh — one-time system integration for the io.github.grootaiinfinity.vpn plugin.
#
# Run as root, once:   pkexec ~/.config/omarchy/plugins/io.github.grootaiinfinity.vpn/install-system.sh
# (the widget's "Set up" button does exactly this).
#
# It installs five files — the kill switch helper, the polkit action, the
# NetworkManager dispatcher hook, the systemd unit and a root-owned copy of the
# uninstaller — to fixed system locations, then reloads the relevant daemons.
# No network access, no downloads, no eval.
#
# Every byte it installs is pinned: the sha256 of each payload file is written
# into the PAYLOAD_SHA256 block below at release time, and root copies each file
# out of a descriptor it opened itself with O_NOFOLLOW into a root-only staging
# directory, verifying the digest of exactly the bytes it staged. Nothing is
# installed unless all five match, and the install reads the plugin folder once
# — never twice, so a file swapped after a check cannot be the file that lands.
#
# An existing file at any destination that omarchy-vpn did not install is never
# overwritten — the script stops and names it.
# Read it before you run it; re-running it is safe (idempotent).

set -euo pipefail
IFS=$'\n\t'
umask 022
export LC_ALL=C

SELF_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)

LIBDIR=/usr/local/lib/omarchy-vpn
POLKIT_ACTION=/usr/share/polkit-1/actions/com.omarchy.vpn.policy
DISPATCHER=/etc/NetworkManager/dispatcher.d/50-omarchy-vpn
UNIT=/etc/systemd/system/omarchy-vpn-killswitch.service

# The complete, fixed list of what root installs: <relative source>:<mode>:<destination>.
# Nothing outside this list is read, staged or written.
PAYLOAD=(
  "system/omarchy-vpn-helper:0755:$LIBDIR/omarchy-vpn-helper"
  "system/com.omarchy.vpn.policy:0644:$POLKIT_ACTION"
  "system/50-omarchy-vpn:0755:$DISPATCHER"
  "system/omarchy-vpn-killswitch.service:0644:$UNIT"
  "uninstall-system.sh:0755:$LIBDIR/uninstall-system.sh"
)

# BEGIN PAYLOAD_SHA256 — generated by tools/update-digests.sh, do not edit by hand
PAYLOAD_SHA256=(
  "a194449adceff6227c57233bed32b8471cb44c4ff08db2b4882d1c1eea2a74c5  system/omarchy-vpn-helper"
  "f6bdea9ffd500fce96f8414a08dedd084d913b33098733e00bc86a547bf1b8d1  system/com.omarchy.vpn.policy"
  "34d090780516a6b1b1a8ad95c2f5f63324310a672a7118382d3e05a34aa3dd8d  system/50-omarchy-vpn"
  "9356fa63c660a382ecf2351b0e2e2f8aa99be19d8acce064f69fd7f46d5b229d  system/omarchy-vpn-killswitch.service"
  "f10511b0746e0988c798ad391ad3f38910f2068ebe09b1d413fe1a3f32028489  uninstall-system.sh"
)
# END PAYLOAD_SHA256

[[ ${EUID:-$(id -u)} -eq 0 ]] || { echo "must run as root (use the widget's Set up button, or sudo)" >&2; exit 1; }

command -v nft     >/dev/null || { echo "nftables is required (pacman -S nftables)" >&2; exit 1; }
command -v nmcli   >/dev/null || { echo "NetworkManager is required" >&2; exit 1; }
command -v python3 >/dev/null || { echo "python3 is required to verify the files being installed" >&2; exit 1; }

# Refuse to clobber a file at one of these paths that belongs to something
# else. Everything this script installs names omarchy-vpn in its own body, so a
# destination that never mentions it was written by another package.
guard_write() {
  local dest=$1
  [[ -e $dest ]] || return 0
  grep -q 'omarchy-vpn' -- "$dest" 2>/dev/null && return 0
  echo "refusing to overwrite $dest — it was not installed by omarchy-vpn" >&2
  echo "  inspect it, move it aside and re-run, or set VPN_FORCE=1 to overwrite" >&2
  [[ ${VPN_FORCE:-0} == 1 ]] || exit 1
  echo "VPN_FORCE=1 — overwriting $dest" >&2
}

entry=""
for entry in "${PAYLOAD[@]}"; do
  guard_write "${entry##*:}"
done

# ---------------------------------------------------------------- staging
#
# The plugin folder lives in the user's home and is writable by that user, so
# root must not treat it as trusted input. Copy every payload file into a
# root-owned directory on /run first, reading each one through a descriptor
# opened with O_NOFOLLOW and hashing the bytes as they are copied, then install
# only from that staging copy — which nothing but root can touch.
#
# This is the whole reason the step below is Python rather than more shell: a
# shell redirect cannot open a file without following symlinks, and `install`
# would reopen the source by path, giving an attacker a second chance to swap
# it after the checks passed.

(( ${#PAYLOAD_SHA256[@]} )) || {
  echo "install-system.sh has no payload digests recorded — this is not a released" >&2
  echo "copy of the plugin. Run tools/update-digests.sh if you are developing it." >&2
  exit 1
}

STAGE=$(mktemp -d /run/omarchy-vpn-install.XXXXXXXX)
chmod 0700 "$STAGE"
cleanup() { rm -rf -- "$STAGE"; }
trap cleanup EXIT

# The uid the files are expected to belong to: whoever asked for the install.
EXPECT_UID=${PKEXEC_UID:-${SUDO_UID:-}}

python3 -I -S - "$SELF_DIR" "$STAGE" "$EXPECT_UID" "${PAYLOAD_SHA256[@]}" <<'PYSTAGE'
"""Stage the payload into a root-owned directory, binding every byte to a digest.

Reads each file through a descriptor this process opened itself with O_NOFOLLOW
at every path component, checks the inode it actually got, and streams it into
the staging directory while hashing. A file that is a symlink, is not a regular
file, has extra hard links, is writable by group or other, or whose bytes do not
hash to the digest committed in install-system.sh, stops the whole install.
"""
import hashlib
import os
import re
import stat
import sys

MAX_FILE = 1 << 20          # payload files are a few KiB; a megabyte is generous
CHUNK = 64 * 1024
DIGEST_RE = re.compile(r"\A[0-9a-f]{64}\Z")
REL_RE = re.compile(r"\A[A-Za-z0-9._-]+(?:/[A-Za-z0-9._-]+)*\Z")


def fail(msg):
    sys.stderr.write("omarchy-vpn install: %s\n" % msg)
    raise SystemExit(1)


def parse_manifest(lines):
    """`<sha256>  <relative path>` per line, as produced by sha256sum."""
    out = {}
    for raw in lines:
        line = raw.strip()
        if not line:
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            fail("malformed digest line: %r" % raw)
        digest, rel = parts[0], parts[1].strip()
        if not DIGEST_RE.match(digest):
            fail("malformed digest for %s" % rel)
        if not REL_RE.match(rel) or ".." in rel.split("/"):
            fail("malformed path in digest list: %r" % rel)
        if rel in out:
            fail("duplicate digest entry for %s" % rel)
        out[rel] = digest
    if not out:
        fail("no payload digests are recorded in install-system.sh — "
             "regenerate them with tools/update-digests.sh")
    return out


def check_inode(st, what, expect_uid, want_dir=False):
    if want_dir:
        if not stat.S_ISDIR(st.st_mode):
            fail("%s is not a directory" % what)
    else:
        if not stat.S_ISREG(st.st_mode):
            fail("%s is not a regular file" % what)
        if st.st_nlink != 1:
            fail("%s has extra hard links" % what)
    if st.st_mode & 0o022:
        fail("%s is writable by group or other" % what)
    if expect_uid is not None and st.st_uid not in (0, expect_uid):
        fail("%s is owned by uid %d, expected root or uid %d"
             % (what, st.st_uid, expect_uid))


def open_nofollow(rel, root_fd, expect_uid):
    """Open `rel` under `root_fd`, refusing a symlink at every component."""
    parts = rel.split("/")
    fd = root_fd
    try:
        for i, name in enumerate(parts):
            last = i == len(parts) - 1
            # O_NOFOLLOW refuses a symlink, but a FIFO or a device node in
            # the same place would block the open before anything can look at
            # it. O_NONBLOCK makes the open return regardless; the fstat below
            # then rejects anything that is not a regular file. On a regular
            # file O_NONBLOCK has no effect.
            flags = os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK | os.O_CLOEXEC
            if not last:
                flags |= os.O_DIRECTORY
            try:
                nfd = os.open(name, flags, dir_fd=fd)
            except OSError as exc:
                fail("cannot open %s: %s" % (rel, exc.strerror))
            if fd != root_fd:
                os.close(fd)
            fd = nfd
            check_inode(os.fstat(fd), rel if last else "/".join(parts[:i + 1]),
                        expect_uid, want_dir=not last)
        return fd
    except BaseException:
        if fd != root_fd:
            os.close(fd)
        raise


def stage_one(in_fd, stage_dir, rel, want_digest):
    dest = os.path.join(stage_dir, rel.replace("/", "_"))
    out_fd = os.open(dest, os.O_WRONLY | os.O_CREAT | os.O_EXCL
                     | os.O_NOFOLLOW | os.O_CLOEXEC, 0o600)
    try:
        _stage_bytes(in_fd, out_fd, rel, want_digest)
    except BaseException:
        # Unverified bytes never outlive the check that rejected them.
        try:
            os.unlink(dest)
        except OSError:
            pass
        raise
    finally:
        os.close(out_fd)
    return dest


def _stage_bytes(in_fd, out_fd, rel, want_digest):
    """Copy in_fd to out_fd, hashing as it goes, and reject bytes that do not
    hash to the digest install-system.sh was released with."""
    digest = hashlib.sha256()
    total = 0
    while True:
        chunk = os.read(in_fd, CHUNK)
        if not chunk:
            break
        total += len(chunk)
        if total > MAX_FILE:
            fail("%s is larger than %d bytes" % (rel, MAX_FILE))
        digest.update(chunk)
        view = memoryview(chunk)
        while view:
            written = os.write(out_fd, view)
            if written <= 0:
                fail("short write staging %s" % rel)
            view = view[written:]
    os.fsync(out_fd)
    got = digest.hexdigest()
    if got != want_digest:
        fail("%s does not match the digest recorded in install-system.sh\n"
             "  expected %s\n  got      %s\n"
             "  The plugin folder does not hold the files this installer was "
             "released with. Nothing has been installed." % (rel, want_digest, got))


def main():
    src_dir, stage_dir, expect_uid_raw = sys.argv[1], sys.argv[2], sys.argv[3]
    manifest = parse_manifest(sys.argv[4:])
    expect_uid = int(expect_uid_raw) if expect_uid_raw else None

    root_fd = os.open(src_dir, os.O_RDONLY | os.O_DIRECTORY
                      | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        st = os.fstat(root_fd)
        if expect_uid is None:
            # Run straight as root with no invoking user to attribute it to;
            # trust whoever owns the checkout, but still require that only they
            # can write it.
            expect_uid = st.st_uid
        check_inode(st, src_dir, expect_uid, want_dir=True)
        staged = []
        try:
            for rel in sorted(manifest):
                in_fd = open_nofollow(rel, root_fd, expect_uid)
                try:
                    staged.append(stage_one(in_fd, stage_dir, rel, manifest[rel]))
                finally:
                    os.close(in_fd)
        except BaseException:
            # All or nothing. A half-staged payload is never installed — the
            # caller stops on our exit status — but leaving one behind would
            # mean a later reader could mistake it for a verified set.
            for path in staged:
                try:
                    os.unlink(path)
                except OSError:
                    pass
            raise
    finally:
        os.close(root_fd)
    sys.stderr.write("omarchy-vpn install: verified %d payload files\n" % len(manifest))


main()
PYSTAGE

# ---------------------------------------------------------------- install
#
# Sources below are the staged copies in a root-owned 0700 directory on tmpfs,
# not the plugin folder. Nothing unprivileged can change them between here and
# the copy.
install -d -m 0755 -o root -g root "$LIBDIR" /var/lib/omarchy-vpn

rel="" mode="" dest="" staged=""
for entry in "${PAYLOAD[@]}"; do
  rel=${entry%%:*}
  mode=${entry#*:}; mode=${mode%%:*}
  dest=${entry##*:}
  staged="$STAGE/${rel//\//_}"
  [[ -f $staged ]] || { echo "internal error: $rel was not staged" >&2; exit 1; }
  install -D -m "$mode" -o root -g root "$staged" "$dest"
done

systemctl daemon-reload
# dispatcher needs the service running to be useful; NM picks the script up live
systemctl try-restart NetworkManager-dispatcher.service >/dev/null 2>&1 || true

# Repair the enablement of an existing install. Versions up to 1.0.0 shipped a
# unit that hooked itself onto network-pre.target, a passive target nothing on
# an Omarchy box ever pulls in — so the unit was "enabled" and yet never ran at
# boot, and the kill switch came back disarmed after every reboot. `reenable`
# rewrites the symlinks from the [Install] section of the unit we just wrote.
UNIT_NAME=omarchy-vpn-killswitch.service
if [[ -e /var/lib/omarchy-vpn/killswitch.enabled ]] \
   || systemctl is-enabled --quiet "$UNIT_NAME" 2>/dev/null; then
  systemctl reenable "$UNIT_NAME" >/dev/null 2>&1 || true
fi

# If the user had the kill switch on, put the rules back now rather than making
# them toggle it off and on again to recover from the boot that missed them.
#
# Apply with the helper directly rather than relying on `systemctl start`: the
# unit is Type=oneshot with RemainAfterExit=yes, so when it is already active
# systemd treats a start as a no-op. After this script has just replaced the
# helper, that would leave the *previously generated* ruleset loaded while the
# new helper sits unused on disk — exactly the situation an upgrade that changes
# the rules is meant to fix. Applying directly is atomic and idempotent; the
# start afterwards only makes systemd's view agree with what is loaded.
if [[ -e /var/lib/omarchy-vpn/killswitch.enabled ]]; then
  "$LIBDIR/omarchy-vpn-helper" killswitch sync || true
  systemctl start "$UNIT_NAME" >/dev/null 2>&1 || true
fi

echo "omarchy-vpn: system integration installed."
echo "  helper      $LIBDIR/omarchy-vpn-helper"
echo "  polkit      $POLKIT_ACTION"
echo "  dispatcher  $DISPATCHER"
echo "  unit        $UNIT"
echo "  uninstaller $LIBDIR/uninstall-system.sh"
if [[ -e /var/lib/omarchy-vpn/killswitch.enabled ]]; then
  echo "Kill switch is enabled and will be re-armed on every boot."
else
  echo "Nothing is enabled yet — turn the kill switch on from the VPN widget."
fi
