#!/usr/bin/env bash
# tools/update-digests.sh — refresh the payload digests inside install-system.sh.
#
# Run from anywhere in the repo after changing any file install-system.sh
# installs. It reads the PAYLOAD array in install-system.sh — the single list of
# what gets installed — hashes exactly those files, and rewrites the block
# between the PAYLOAD_SHA256 markers. The list and the digests therefore cannot
# drift apart; tests/run.sh fails if they have.
#
#   tools/update-digests.sh          rewrite the block
#   tools/update-digests.sh --check  exit 1 if the block is out of date

set -euo pipefail
IFS=$'\n\t'
export LC_ALL=C

REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
INSTALLER="$REPO/install-system.sh"
BEGIN='# BEGIN PAYLOAD_SHA256'
END='# END PAYLOAD_SHA256'

mode=${1:-write}
[[ $mode == write || $mode == --check ]] || { echo "usage: ${0##*/} [--check]" >&2; exit 2; }

# The payload paths, in declaration order, from the PAYLOAD array itself.
mapfile -t rels < <(
  sed -n '/^PAYLOAD=(/,/^)/p' "$INSTALLER" \
    | sed -n 's/^[[:space:]]*"\([^:"]*\):.*/\1/p'
)
(( ${#rels[@]} )) || { echo "no PAYLOAD entries found in install-system.sh" >&2; exit 1; }

block=$'\n'
for rel in "${rels[@]}"; do
  [[ -f "$REPO/$rel" ]] || { echo "PAYLOAD names a missing file: $rel" >&2; exit 1; }
  block+="  \"$(sha256sum < "$REPO/$rel" | cut -d' ' -f1)  $rel\""$'\n'
done
new="${BEGIN} — generated by tools/update-digests.sh, do not edit by hand
PAYLOAD_SHA256=($block)
${END}"

current=$(sed -n "/^${BEGIN}/,/^${END}/p" "$INSTALLER")
[[ -n $current ]] || { echo "PAYLOAD_SHA256 markers are missing from install-system.sh" >&2; exit 1; }

if [[ $current == "$new" ]]; then
  [[ $mode == --check ]] && echo "payload digests are up to date"
  exit 0
fi

if [[ $mode == --check ]]; then
  echo "payload digests in install-system.sh are out of date — run tools/update-digests.sh" >&2
  diff <(printf '%s\n' "$current") <(printf '%s\n' "$new") || true
  exit 1
fi

tmp=$(mktemp "$REPO/.install-system.sh.XXXXXX")
trap 'rm -f -- "$tmp"' EXIT
awk -v begin="$BEGIN" -v end="$END" -v repl="$new" '
  index($0, begin) == 1 { print repl; skip = 1; next }
  skip && index($0, end) == 1 { skip = 0; next }
  !skip { print }
' "$INSTALLER" > "$tmp"
chmod --reference="$INSTALLER" "$tmp"
mv -f -- "$tmp" "$INSTALLER"
trap - EXIT
echo "updated ${#rels[@]} payload digests in install-system.sh"
